### ISSUE TITLE
Test keyboard shortcuts in o8build

### ISSUE THREAD

**Issue by db0** [kellyelton/OCTGN#875]
```<cardaction menu="Prioritize" default="False" shortcut="Ctrl+=" execute="prioritize" />```

This fails during game hosting, due to `=` not being able to be parsed by the KeyConverter. We should check these in o8build and yell at the dev.

```
WARN  2013-05-24 22:57:31,145 3.1.34.126 [6] Octgn.Controls.HostGameSettings [(null)] - Start Game Error
 System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Requested value '=' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.Windows.Input.KeyConverter.GetKey(String keyToken, CultureInfo culture)
   at System.Windows.Input.KeyConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object source)
   at System.Windows.Input.KeyGestureConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object source)
   at Octgn.Play.Group.<CreateShortcuts>b__3(GroupAction action) in c:\Program Files (x86)\Jenkins\workspace\OCTGN-Release\octgnFX\Octgn\Play\Group.cs:line 185
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Octgn.Play.Group..ctor(Player owner, Group def) in c:\Program Files (x86)\Jenkins\workspace\OCTGN-Release\octgnFX\Octgn\Play\Group.cs:line 57
   at Octgn.GameEngine..ctor(Game def, String nickname, Boolean isLocal) in c:\Program Files (x86)\Jenkins\workspace\OCTGN-Release\octgnFX\Octgn\GameEngine.cs:line 53
   at Octgn.Controls.HostGameSettings.StartLocalGame(Game game, String name, String password) in c:\Program Files (x86)\Jenkins\workspace\OCTGN-Release\octgnFX\Octgn\Controls\HostGameSettings.xaml.cs:line 224
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: Requested value '=' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.Windows.Input.KeyConverter.GetKey(String keyToken, CultureInfo culture)
   at System.Windows.Input.KeyConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object source)
   at System.Windows.Input.KeyGestureConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object source)
   at Octgn.Play.Group.<CreateShortcuts>b__3(GroupAction action) in c:\Program Files (x86)\Jenkins\workspace\OCTGN-Release\octgnFX\Octgn\Play\Group.cs:line 185
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Octgn.Play.Group..ctor(Player owner, Group def) in c:\Program Files (x86)\Jenkins\workspace\OCTGN-Release\octgnFX\Octgn\Play\Group.cs:line 57
   at Octgn.GameEngine..ctor(Game def, String nickname, Boolean isLocal) in c:\Program Files (x86)\Jenkins\workspace\OCTGN-Release\octgnFX\Octgn\GameEngine.cs:line 53
   at Octgn.Controls.HostGameSettings.StartLocalGame(Game game, String name, String password) in c:\Program Files (x86)\Jenkins\workspace\OCTGN-Release\octgnFX\Octgn\Controls\HostGameSettings.xaml.cs:line 224
   at System.Threading.Tasks.Task.Execute()<---

```

**Comment by kellyelton** [comment]
Looks like I implemented this like right after you asked for it but never updated the ticket

https://github.com/kellyelton/OCTGN/commit/8b44a80929ff17ab57c04dd985a2fd963d65c58f
